### ISSUE TITLE
hundleGoBlog, hundleGoPortfolioについて

### ISSUE THREAD

**Issue by foreverainn** [yamashin01/qin_portfolio#19]
```javascript
 <Button color={theme.colorScheme === 'dark' ? "gray" : "dark"} radius="xl" onClick={handleGoBlog}>
              View All
            </Button>
```
`index.tsx`で上のように書かれていますが、mantineのButtonにnextのLinkを使う書き方の方が自然だと思います。
少し特殊な書き方をするので、下の記事の**usage-with-nextjs**を参考にしましょう！
https://mantine.dev/core/button/#usage-with-nextjs

**Comment by yamashin01** [comment]
@kotu-kotuo 
ありがとうございます。
改修しました。
