### ISSUE TITLE
hover:cursor-pointerについて

### ISSUE THREAD

**Issue by foreverainn** [yamashin01/qin_portfolio#20]
cursor-pointerは「ホバーした時にカーソルが指マークになるプロパティ」なので、Tailwindのhover:をつけなくても正常に効きます。
なのでhover:は不要です。

**Comment by yamashin01** [comment]
@kotu-kotuo 
そうなんですね、知らなかった。
ありがとうございます。

**Comment by foreverainn** [comment]
![image](https://user-images.githubusercontent.com/52486487/190966343-15417d2d-4a76-4a59-83a1-b18cfd6e8a76.png)
全部確認しました！
コミットメッセージにIssueの番号を追加するとIssue内でコミットが表示されるので次の機会があればお試しください
ex... 「cursor-pointer修正 #20」
