### ISSUE TITLE
StarアイコンとForkアイコンの整列

### ISSUE THREAD

**Issue by natsumi-h** [yamashin01/qin_portfolio#35]
こちら、divクラスのclassNameに`flex`と、`items-center
` を追加すると、Starとforkのアイコンが上下中央になってきれいに整列されると思います！

https://github.com/yamashin01/qin_portfolio/blob/e5e2fa89a32348d6d696a8b613d20d5b682b0e8c/src/components/Github.tsx#L53-L58

**Comment by yamashin01** [comment]
ありがとうございます。
確かにおっしゃるとおりですね。

ご指摘のとおり修正しました。
