### ISSUE TITLE
Languageの表示

### ISSUE THREAD

**Issue by natsumi-h** [yamashin01/qin_portfolio#37]
Languagesのパーセンテージバーのところですが、数字の大きいものから順に左側から表示させるのであれば、

```
languages(first: 100, orderBy: { field: SIZE, direction: DESC }) {
                totalCount...
                }
```
などとしてSIZEの大きいものから表示させると良いかなと思いました。

https://github.com/yamashin01/qin_portfolio/blob/e5e2fa89a32348d6d696a8b613d20d5b682b0e8c/src/utils/query.ts#L14-L21

**Comment by yamashin01** [comment]
ありがとうございます。
サイズ順にするか、言語順にするかは悩みどころですね。
