### ISSUE TITLE
githubのパーセンテージ

### ISSUE THREAD

**Issue by tocchi-739** [yamashin01/qin_portfolio#39]
https://github.com/yamashin01/qin_portfolio/blob/main/src/components/Github.tsx

%の表示で小数点以下の桁数が異なるのが気になりました。好みもあるかと思いますが😅

### 現状
22行目（割合を算出）
`const percentage = language.size / repositoryBasicData.languages.totalSize * 100;`

68行目（有効桁数２桁に→0.の場合に0.xxとなってしまう）
`<span className="text-gray-600 mr-4">{language.percentage.toPrecision(2)}%</span>`

### 自分はこのようにしました。
`const percentage = Math.round((language.size / repositoryBasicData.languages.totalSize )* 1000)/10;`
`<span className="text-gray-600 mr-4">{language.percentage}%</span>`

*1000にした上で、Math.roundを使い小数点第一位で四捨五入
その後10で割ることで、xx.xの表示に

参考（Math.round　MDN）
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Math/round

**Comment by yamashin01** [comment]
ありがとうございます。
確かに桁数を揃えた方が良いですね。
ご指摘のとおり修正しました。
