### ISSUE TITLE
ジェネリクスに型をいれましょう

### ISSUE THREAD

**Issue by k-logic563** [yamashin01/qin_portfolio#40]
以下、取得するデータに型をつけることができます。
https://github.com/yamashin01/qin_portfolio/blob/3267165e988c4fbcc3002befd6df5495f39cc4b1/src/components/Github.tsx#L12

このようにすればいいかもしれません。
`useQuery< GitHubRepoType>(GET_REPO_QUERY)`

参考は公式から！
https://www.apollographql.com/docs/react/development-testing/static-typing/

**Comment by k-logic563** [comment]
これができると以下の型付けが必要なくなります。
https://github.com/yamashin01/qin_portfolio/blob/3267165e988c4fbcc3002befd6df5495f39cc4b1/src/components/Github.tsx#L18

**Comment by yamashin01** [comment]
ありがとうございます。
`GitHubRepoType`では`user`が定義されておらずエラーとなるため、新たに下記の型を作ってuserQueryに使用しました。

```
export type GitHubType = {
    user: {
        repositories : {
            edges : {
                node : GitHubRepoType; 
            }[];
        }
    }
}
```
