### ISSUE TITLE
GraphQLの指定

### ISSUE THREAD

**Issue by tocchi-739** [yamashin01/qin_portfolio#42]
次のように、privacyの指定や、orderByで並び替えをしているのが良いなと思いました！
`repositories(last: 5, privacy: PUBLIC, orderBy: {field: UPDATED_AT, direction: ASC}) {`

https://github.com/yamashin01/qin_portfolio/blob/main/src/utils/query.ts

**Comment by yamashin01** [comment]
ありがとうございます。
どこかのサイトか何かの引用なので、自分で考えたわけではないのですが笑
