### ISSUE TITLE
省略してかけます

### ISSUE THREAD

**Issue by k-logic563** [yamashin01/qin_portfolio#43]
https://github.com/yamashin01/qin_portfolio/blob/3267165e988c4fbcc3002befd6df5495f39cc4b1/src/components/Github.tsx#L32

以下のように書けます。
```
{basicData: repositoryBasicData, languageDataList, langAreaList};
```

**Comment by yamashin01** [comment]
ありがとうございます。
確かにいただいた書き方でも問題なく動きました。

型名が変数と同じ場合は省略できるという認識で良いでしょうか？
